### ISSUE TITLE
Manager.RemoveNode() should take a node index

### ISSUE THREAD

**Issue by Dnawrkshp** [Resourceful-Rails-Team/resourceful-rails-game#53]
Currently the Manager.RemoveNode() method takes a NodeId as its second argument. This argument is then used to find and remove the requested element from the list.
The issue with this is that when the path contains duplicate NodeIds this second argument becomes ambiguous. The proposed change will resolve this ambiguity by requiring the index in the list (unique) be given instead of the NodeId.

**Comment by thomabel** [comment]
I changed the second argument to accept an integer index for the node in the path array.
