### ISSUE TITLE
Add context to GameInput

### ISSUE THREAD

**Issue by Dnawrkshp** [Resourceful-Rails-Team/resourceful-rails-game#54]
Currently there is no way to prevent the game's highlight and interact-with-nodes logic from triggering.

The UI sometimes needs to force the user to interact with a popup before they can continue interacting with the rest of the game. Ideally it should be possible to set a flag in the GameInput class to turn off the board interaction. I'm open to other ideas though.

**Comment by ChristianNoelSchmid** [comment]
That sounds great - I'll add a public ~~method `SetEnabled(bool)`~~ field `IsEnabled` to `GameInput`

**Comment by ChristianNoelSchmid** [comment]
Alright, should be fixed (via the new PR)
