### ISSUE TITLE
Pathfinding Default City Value

### ISSUE THREAD

**Issue by thomabel** [Resourceful-Rails-Team/resourceful-rails-game#89]
The default value for cities is 0. Christian thought this was 1, so please check if there are any issues.

**Comment by ChristianNoelSchmid** [comment]
Because `Manager` CityId is never written to except via the map editor, I created a getter named `CityID`, which checks if the `NodeType` of the `Node` is a city type before giving the index. Otherwise it just returns `-1`. This should fix the issue.
